# These are all the cops that are disabled in the default configuration.

Style/Lambda:
  Description: "Use the new lambda literal syntax for single-line blocks."
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Description: "Avoid chaining a method call on a do...end block."
  Enabled: false

Style/SymbolArray:
  Description: "Use %i or %I for arrays of symbols."
  Enabled: false

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: false

Style/EmptyLiteral:
  Description: "Prefer literals to Array.new/Hash.new/String.new."
  Enabled: false

Style/ClassAndModuleChildren:
  Description: "Checks style of children classes and modules."
  Enabled: false

Metrics/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Enabled: false

Metrics/MethodLength:
  Description: "Avoid methods longer than 10 lines of code."
  Enabled: false

Metrics/ParameterLists:
  Description: "Avoid parameter lists longer than three or four parameters."
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: "Avoid complex methods."
  Enabled: false

Layout/AlignArray:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  Enabled: false

Style/UnneededPercentQ:
  Description: "Checks for %q/%Q when single quotes or double quotes would do."
  Enabled: false

Style/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/Alias:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/Encoding:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

#################### Lint ################################
### Warnings
Lint/AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: false
